import { useState } from 'react';
import { Icon } from '../ui/Icon';
import { languages } from '../../i18n';
import type { AppRoute, Candidate, Language } from '../../types/domain';

const tabs:Exclude<AppRoute,'Profile'>[]=['Candidate Dossiers','Access Codes','Analytics'];
type Panel='search'|'notifications'|'profile'|null;
interface HeaderProps { active:string; navigate:(route:AppRoute)=>void; candidates:Candidate[]; openCandidate:(id:string)=>void; openProfile:()=>void; onLogout:()=>void; language:Language; setLanguage:(language:Language)=>void; hasSidebar:boolean; desktopSidebarOpen:boolean; mobileSidebarOpen:boolean; toggleSidebar:()=>void }
interface NotificationProps { tone:string; title:string; text:string; time:string; onOpen:()=>void }

export function Header({active,navigate,candidates,openCandidate,openProfile,onLogout,language,setLanguage,hasSidebar,desktopSidebarOpen,mobileSidebarOpen,toggleSidebar}:HeaderProps) {
  const [panel,setPanel]=useState<Panel>(null);
  const [search,setSearch]=useState('');
  const results=search.trim()?candidates.filter(c=>(c.name+' '+c.company+' '+c.telegram).toLowerCase().includes(search.toLowerCase())).slice(0,6):[];
  const close=()=>{setPanel(null);setSearch('')};
  const closeMobileSidebar=()=>{if(mobileSidebarOpen)toggleSidebar()};
  return <header className="topbar"><button className="brand" onClick={()=>{close();closeMobileSidebar();navigate('Candidate Dossiers')}} aria-label="Open candidate dossiers">CEOMENTALITY</button><div className="system-label">access system</div>{hasSidebar&&<button className="header-sidebar-toggle header-sidebar-toggle-mobile" onClick={toggleSidebar} aria-label={mobileSidebarOpen?'Hide filters':'Show filters'} aria-expanded={mobileSidebarOpen}><Icon name="sidebar" size={20}/></button>}<nav className="main-nav">{tabs.map(t=><button key={t} className={active===t?'active':''} onClick={()=>{close();closeMobileSidebar();navigate(t)}}>{t}</button>)}</nav><div className="top-actions">{hasSidebar&&<button className="header-sidebar-toggle header-sidebar-toggle-desktop" onClick={toggleSidebar} aria-label={desktopSidebarOpen?'Hide filters':'Show filters'} aria-expanded={desktopSidebarOpen}><Icon name="sidebar" size={20}/></button>}<button className={`language-switch ${language}`} onClick={()=>setLanguage(language==='en'?'ru':'en')} aria-label="Switch interface language"><span>{languages.en}</span><i/><span>{languages.ru}</span></button>
    <button className={`icon-btn ${panel==='search'?'is-open':''}`} aria-label="Search" onClick={()=>setPanel(panel==='search'?null:'search')}><Icon name="search"/></button>
    <button className={`icon-btn notification-trigger ${panel==='notifications'?'is-open':''}`} aria-label="Notifications" onClick={()=>setPanel(panel==='notifications'?null:'notifications')}><Icon name="bell"/><span className="notification-dot"/></button>
    <button className={`avatar ${panel==='profile'?'is-open':''}`} onClick={()=>setPanel(panel==='profile'?null:'profile')}>CM</button>
  </div>
  {panel&&<button className="header-scrim" aria-label="Close" onClick={close}/>}
  {panel==='search'&&<section className="header-popover search-popover"><div className="popover-kicker">Global search</div><label className="global-search-field"><Icon name="search"/><input autoFocus value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search candidates, codes or drops..."/><kbd>ESC</kbd></label><div className="search-results">{!search&&<div className="search-hint"><strong>Search across the access system</strong><p>Candidate and demo data are available now. Full server search will use the future API endpoint.</p></div>}{search&&results.map(c=><button key={c.id} onClick={()=>{close();openCandidate(c.id)}}><span className="result-avatar">{c.initials}</span><span><strong>{c.name}</strong><small>{c.role} · {c.company}</small></span><em>{c.status}</em></button>)}{search&&!results.length&&<div className="search-empty">No matching records</div>}</div><footer><span>Local MVP index</span><span>Backend-ready search contract</span></footer></section>}
  {panel==='notifications'&&<section className="header-popover notifications-popover"><div className="popover-title"><div><span>Activity center</span><h2>Notifications</h2></div><button onClick={()=>setPanel(null)}>Mark all read</button></div><div className="notification-list"><Notification tone="blue" title="New candidate application" text="Alexei Petrov submitted a product access application." time="2 min ago" onOpen={()=>{close();navigate('Candidate Dossiers')}}/><Notification tone="green" title="Code redeemed" text="Wave 01 access code was successfully activated." time="18 min ago" onOpen={()=>{close();navigate('Access Codes')}}/><Notification tone="orange" title="Drop expires soon" text="Spring Collection Drop closes in 3 days." time="1 hour ago" onOpen={()=>{close();navigate('Access Codes')}}/></div><button className="popover-footer-action" onClick={()=>setPanel(null)}>View all activity <Icon name="arrow" size={14}/></button></section>}
  {panel==='profile'&&<section className="header-popover profile-menu"><div className="profile-menu-head"><span className="profile-menu-avatar">CM</span><div><strong>Club Manager</strong><small>manager@ceomentality.club</small></div></div><div className="profile-role"><span>Workspace role</span><b>Founder access</b></div><button onClick={()=>{close();openProfile()}}>Profile & settings <Icon name="arrow" size={14}/></button><button onClick={()=>navigate('Candidate Dossiers')}>Switch workspace</button><button className="danger-menu" onClick={()=>{close();onLogout()}}>Sign out</button></section>}
  </header>;
}

function Notification({tone,title,text,time,onOpen}:NotificationProps) { return <button className="notification-item" onClick={onOpen}><span className={`notification-mark ${tone}`}/><span><strong>{title}</strong><p>{text}</p><time>{time}</time></span></button> }
