import { useEffect, useState } from 'react';
import type { AccessBatch, BatchDraft, CodeType, WorkspaceFilters } from '../../types/domain';
import type { BatchSort, BatchTab } from './selectors';
interface AccessProps { drops:AccessBatch[]; query:string; filters:WorkspaceFilters; resetFilters?:()=>void; createDrop:()=>void; generateBatch:(draft:BatchDraft)=>void; closeDrop:(id:string)=>void; exportData:()=>void; notify?:(message:string)=>void }
import { Icon } from '../../components/ui/Icon';
import { CustomSelect } from '../../components/ui/CustomSelect';
import { DateRangePicker } from '../../components/ui/DateRangePicker';
import { Modal } from '../../components/ui/Modal';
import { MetricStrip, Mini } from '../../components/ui/DataDisplay';
import { selectBatches } from './selectors';
export function Access({drops,query,filters,resetFilters,createDrop,generateBatch,closeDrop,exportData,notify=()=>{}}:AccessProps) {
 const [batchTab,setBatchTab]=useState<BatchTab>('All');
 const [codeType,setCodeType]=useState<CodeType>('Single-use');
 const [quantity,setQuantity]=useState(200);
 const [advanced,setAdvanced]=useState(false);
 const [view,setView]=useState('list');
 const [sort,setSort]=useState<BatchSort>('Recently created');
 const [openBatchMenu,setOpenBatchMenu]=useState<string|null>(null);
 const [selectedBatch,setSelectedBatch]=useState<AccessBatch|null>(null);
 const [activityExpanded,setActivityExpanded]=useState(false);
 const [assignedDrop,setAssignedDrop]=useState('Spring Collection Drop');
 const [validity,setValidity]=useState('May 14 - May 31, 2025');
 useEffect(()=>{const close=(e:PointerEvent)=>{const target=e.target;if(target instanceof Element&&!target.closest('.batch-actions'))setOpenBatchMenu(null)};document.addEventListener('pointerdown',close);return()=>document.removeEventListener('pointerdown',close)},[]);
 const list=selectBatches(drops,query,filters,batchTab,sort);
 const issued=drops.reduce((a,d)=>a+d.issued,0), redeemed=drops.reduce((a,d)=>a+d.redeemed,0);
 const exportBatch=(d:AccessBatch)=>{const blob=new Blob([JSON.stringify(d,null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const link=document.createElement('a');link.href=url;link.download=`${d.id}-batch.json`;link.click();URL.revokeObjectURL(url);notify(`${d.name} exported`)};
 return <><main className="content access-codes">
   <div className="page-title-row"><div><div className="pretitle">Access Codes</div><h1>access codes</h1><p>Create and manage unique invite codes for private drops.</p></div><div className="button-row"><button className="primary-btn" onClick={createDrop}><Icon name="plus"/>Create drop</button><button className="outline-btn" onClick={exportData}><Icon name="download"/>Export</button></div></div>
   <MetricStrip items={[{label:'Codes issued',value:issued.toLocaleString(),delta:'+20% vs last month'},{label:'Active codes',value:drops.filter(d=>d.status==='Active').length,delta:'+12%'},{label:'Redeemed',value:redeemed.toLocaleString(),delta:'+18%'},{label:'Expired',value:drops.filter(d=>d.status==='Closed').length,delta:'-8%'},{label:'Conversion',value:`${issued?((redeemed/issued)*100).toFixed(1):0}%`,delta:'+1.5pp'}]}/>
   <section className="access-layout">
     <section className="panel create-panel"><h3>Create code batch</h3><label>Assigned drop</label><CustomSelect className="batch-select" value={assignedDrop} options={['Spring Collection Drop','Partner Access','Waitlist Release']} onChange={setAssignedDrop}/><label>Code type</label><div className="segmented"><button className={codeType==='Single-use'?'active':''} onClick={()=>setCodeType('Single-use')}>Single-use</button><button className={codeType==='Multi-use'?'active':''} onClick={()=>setCodeType('Multi-use')}>Multi-use</button></div><label>Quantity</label><div className="stepper"><button aria-label="Decrease quantity" onClick={()=>setQuantity(Math.max(1,quantity-50))}><Icon name="minus" size={14}/></button><input aria-label="Code quantity" type="number" min="1" max="100000" step="1" value={quantity} onChange={e=>setQuantity(Math.max(1,Number(e.target.value)||1))}/><button aria-label="Increase quantity" onClick={()=>setQuantity(quantity+50)}><Icon name="plus" size={14}/></button></div><label>Validity</label><DateRangePicker value={validity} onChange={setValidity}/><button className={`advanced ${advanced?'open':''}`} onClick={()=>setAdvanced(!advanced)}>Advanced options <i className="button-chevron"/></button>{advanced&&<div className="advanced-fields"><label><input type="checkbox"/> Prefix by wave</label><label><input type="checkbox"/> Notify managers</label></div>}<button className="generate" onClick={()=>generateBatch({name:assignedDrop,description:`${codeType} code batch`,issued:quantity,validity,codeType})}>Generate codes</button></section>
     <section className="panel batches-panel"><div className="batch-toolbar"><h3>Code batches</h3><div className="tabs batch-tabs">{(['All','Active','Scheduled','Expired'] as BatchTab[]).map(tab=><button key={tab} className={batchTab===tab?'active':''} onClick={()=>setBatchTab(tab)}>{tab} ({tab==='All'?drops.length:drops.filter(d=>tab==='Expired'?d.status==='Closed':d.status===tab).length})</button>)}</div><div className="batch-toolbar-actions"><CustomSelect className="batch-sort" value={sort} options={['Recently created','Name A-Z','Highest issued','Most redeemed']} onChange={setSort}/><button className={`view-switch ${view}`} aria-label={`Switch to ${view==='list'?'grid':'list'} view`} onClick={()=>setView(view==='list'?'grid':'list')}><Icon name="grid" size={14}/><span/><Icon name="list" size={15}/></button></div></div><div className={`batch-list ${view}`}>{list.map(d=><div className="batch-row functional" key={d.id}><span className={`status-dot ${d.status==='Active'?'green':'orange'}`}/><div><strong>{d.name}</strong><p>{d.description}</p></div><Mini label="Issued" value={d.issued}/><Mini label="Redeemed" value={d.redeemed}/><Mini label="Remaining" value={d.issued-d.redeemed}/><div className="validity"><strong>{d.validity}</strong><label>Validity</label></div><span className="tag">{d.status}</span><div className={`batch-actions ${openBatchMenu===d.id?'open':''}`}><button className="more" aria-label={`Actions for ${d.name}`} onClick={()=>setOpenBatchMenu(openBatchMenu===d.id?null:d.id)}><Icon name="more" size={18}/></button>{openBatchMenu===d.id&&<div className="batch-menu"><button onClick={()=>{setSelectedBatch(d);setOpenBatchMenu(null)}}>View batch details</button><button onClick={()=>{navigator.clipboard?.writeText(d.code||d.name);notify('Batch code copied');setOpenBatchMenu(null)}}>Copy access code</button><button onClick={()=>{exportBatch(d);setOpenBatchMenu(null)}}>Export this batch</button><button className="danger" onClick={()=>{closeDrop(d.id);notify(`${d.name} status updated`);setOpenBatchMenu(null)}}>{d.status==='Active'?'Close batch':'Reopen batch'}</button></div>}</div></div>)}</div></section>
   </section>
   <section className="bottom-grid"><section className="panel timeline"><h3>Issuance timeline</h3><div className="timeline-line"/><div className="timeline-items">{drops.map((d,i)=><div className={`timeline-item ${i===0?'green':i===2?'purple':i===3?'orange':''}`} style={{left:`${i*27}%`}} key={d.id}><span/><strong>{d.name}</strong><p>{d.validity.split(' - ')[0]}<br/>{d.issued} codes</p></div>)}</div><button className="wide-outline" onClick={()=>{setBatchTab('All');resetFilters?.();document.querySelector('.batches-panel')?.scrollIntoView({behavior:'smooth',block:'start'});notify('Showing all code batches')}}>View all batches <Icon name="arrow" size={14}/></button></section><section className={`panel activity ${activityExpanded?'expanded':''}`}><h3>Recent code activity</h3><div className="activity-list">{[['Code redeemed','WAVE01-7KX9-2821','Wave 01','2m ago'],['Code issued','WAVE02-R8M2-J3QH','Wave 02','8m ago'],['Code redeemed','PARTNER-3LQJ-8FP2','Partner Access','15m ago'],['Code expired','WAIT-6ZP4-V9DN','Waitlist Release','1h ago'],['Code issued','WAVE02-R8M2-J3QH','Wave 02','2h ago']].concat(activityExpanded?[['Code redeemed','WAVE01-A7P4-K2LM','Wave 01','3h ago'],['Code issued','PARTNER-Q8T2-N6PX','Partner Access','5h ago']]:[]).map((a,i)=><div className="activity-row" key={i}><span className={`activity-icon ${i===0||i===2?'green':i===3?'orange':''}`}/><b>{a[0]}</b><strong>{a[1]}</strong><em>{a[2]}</em><time>{a[3]}</time></div>)}</div><button className="wide-outline" onClick={()=>setActivityExpanded(!activityExpanded)}>{activityExpanded?'Collapse activity':'View all activity'} <Icon name="arrow" size={14}/></button></section></section>
   <p className="confidential"><Icon name="lock" size={13}/>Access codes are unique and confidential. Do not share codes publicly.</p>
 </main>{selectedBatch&&<Modal title={selectedBatch.name} onClose={()=>setSelectedBatch(null)}><div className="batch-detail-modal"><div><span>Status</span><strong>{selectedBatch.status}</strong></div><div><span>Code</span><strong>{selectedBatch.code}</strong></div><div><span>Issued</span><strong>{selectedBatch.issued}</strong></div><div><span>Redeemed</span><strong>{selectedBatch.redeemed}</strong></div><div><span>Remaining</span><strong>{selectedBatch.issued-selectedBatch.redeemed}</strong></div><div><span>Validity</span><strong>{selectedBatch.validity}</strong></div></div><div className="form-actions"><button className="outline-btn" onClick={()=>navigator.clipboard?.writeText(selectedBatch.code)}>Copy code</button><button className="primary-btn" onClick={()=>exportBatch(selectedBatch)}>Export batch</button></div></Modal>}</>;
}
