import { useEffect, useRef, useState } from 'react';
import { Icon } from './Icon';

interface DateRangePickerProps { value:string; onChange?:(value:string)=>void }
type CalendarView = 'days'|'months'|'years';

export function DateRangePicker({value,onChange}:DateRangePickerProps) {
 const [open,setOpen]=useState(false),[month,setMonth]=useState(new Date(2025,4,1)),[start,setStart]=useState<number|null>(14),[end,setEnd]=useState<number|null>(31),[view,setView]=useState<CalendarView>('days');
 const ref=useRef<HTMLDivElement>(null);
 useEffect(()=>{const close=(event:PointerEvent|KeyboardEvent)=>{if(event instanceof KeyboardEvent?event.key==='Escape':!ref.current?.contains(event.target as Node))setOpen(false)};document.addEventListener('pointerdown',close);document.addEventListener('keydown',close);return()=>{document.removeEventListener('pointerdown',close);document.removeEventListener('keydown',close)}},[]);
 const year=month.getFullYear(),m=month.getMonth(),days=new Date(year,m+1,0).getDate(),offset=(new Date(year,m,1).getDay()+6)%7;
 const choose=(day:number)=>{if(!start||end){setStart(day);setEnd(null)}else{setStart(Math.min(start,day));setEnd(Math.max(start,day))}};
 const apply=()=>{if(!start)return;const monthName=month.toLocaleString('en',{month:'short'});onChange?.(`${monthName} ${start}${end?` - ${monthName} ${end}`:''}, ${year}`);setOpen(false)};
 const years=Array.from({length:12},(_,i)=>2020+i),months=Array.from({length:12},(_,i)=>new Date(2025,i,1).toLocaleString('en',{month:'short'}));
 return <div className={`date-picker ${open?'open':''}`} ref={ref}><button type="button" className="field date-trigger" onClick={()=>setOpen(!open)}><Icon name="calendar" size={16}/><span>{value}</span><i/></button>{open&&<section className="calendar-popover"><header><button type="button" onClick={()=>view==='days'?setMonth(new Date(year,m-1,1)):setView('years')}><Icon name="left" size={16}/></button><button type="button" className="calendar-title" onClick={()=>setView('years')}>{view==='years'?'Select year':view==='months'?`${year} · Select month`:`${month.toLocaleString('en',{month:'long'})} ${year}`}</button><button type="button" onClick={()=>view==='days'?setMonth(new Date(year,m+1,1)):setView('days')}><Icon name="arrow" size={16}/></button></header><div className="calendar-stage">{view==='years'?<div className="calendar-choice-grid years">{years.map(y=><button type="button" className={y===year?'selected':''} key={y} onClick={()=>{setMonth(new Date(y,m,1));setView('months')}}>{y}</button>)}</div>:view==='months'?<div className="calendar-choice-grid">{months.map((name,index)=><button type="button" className={index===m?'selected':''} key={name} onClick={()=>{setMonth(new Date(year,index,1));setView('days')}}>{name}</button>)}</div>:<><div className="calendar-week">{['Mo','Tu','We','Th','Fr','Sa','Su'].map(x=><span key={x}>{x}</span>)}</div><div className="calendar-days">{Array.from({length:42},(_,index)=>{const day=index-offset+1;return day>0&&day<=days?<button type="button" key={index} className={`${day===start||day===end?'edge':''} ${end&&start&&day>start&&day<end?'range':''}`} onClick={()=>choose(day)}>{day}</button>:<span key={index}/>})}</div></>}</div><footer><button type="button" onClick={()=>{setStart(null);setEnd(null)}}>Clear</button><button type="button" className="calendar-apply" onClick={apply} disabled={!start}>Apply dates</button></footer></section>}</div>;
}
